collections:
  authors:
    output: true

baseurl: ""
url: "https://oboe.github.io/"

highlighter: rouge
input: "GFM"
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"